### ISSUE TITLE
dependencies are duplicated  + add version specs 

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos_utils#5]
dependencies are duplicated in setup.py and requirements.txt. Also, should add version specs to all deps

**Comment by builderjer** [comment]
I can help on this. Which file should they be in?

**Comment by NeonDaniel** [comment]
In OSM, we put them in `setup.py` and `requirements.txt` just included `.` to install from setup.py
I think that's the best option for consistency? @ChanceNCounter did that one iirc
 https://github.com/OpenVoiceOS/ovos_skill_manager

**Comment by ChanceNCounter** [comment]
To be honest, I did about 10 minutes of research, another 10 minutes of trying to break it, and concluded that StackOverflow was right this time. I have no idea if that's a best practice or a kludge.

**Comment by NeonDaniel** [comment]
Alternate method I started using (before I knew `.` was a valid requirement) below. One new nice side-effect is PyCharm validation of requirements files
https://github.com/NeonGeckoCom/neon-skill-utils/blob/e43adf3fe05774c031849c1a62b2cc6fe00a8556/setup.py#L34-L39
